/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.saka.plantuml.viewer;

import static org.hamcrest.CoreMatchers.allOf;
import static org.hamcrest.CoreMatchers.containsString;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.collect.ImmutableMap;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = App.class)
@AutoConfigureMockMvc
public class AppTest {

  @Autowired
  private MockMvc mvc;

  @Test
  public void postSvg() throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    mvc
      .perform(
        post("/svg/")
          .contentType(MediaType.APPLICATION_JSON)
          .content(mapper.writeValueAsString(
            ImmutableMap.of(
              "plantUml", "@startuml\r\n@enduml"
            ))))
      .andExpect(status().is(HttpStatus.CREATED.value()))
      .andExpect(content().string(
        allOf(
          containsString("@startuml"),
          containsString("/raw")))
      );
  }
}
